CREATE TABLE [dbo].[pm](
	[id] [int] NOT NULL,
	[date] [date] NULL,
	[val] [int] NULL,
 CONSTRAINT [PK_pm] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

